In [24]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

Extraction des Outputs de 2022, dans un premiers temps on s'intéresse aux services d'Urgence, de MCO et de SSR. On pourra ajouter d'autres services par la suite (Psychiatrie par exemple)

In [25]:
FINESS = pd.read_excel("finess.xlsx")
FINESS = FINESS.drop(FINESS.columns[[1,2,4]],axis=1)
FINESS = FINESS.rename(columns={"FINESS":"FI","Statut Juridique":"Statut"})

SYGEN2022 = pd.read_csv("SAE/2022/SYGEN_2022r.csv", sep=";", encoding="latin-1")
Data = SYGEN2022[['FI','ETPSAL_TOT','EFFLIB_TOT','ETP_INFSANSSPE','ETP_INFAVECSPE','ETP_AID','ETP_DIR','ETP_DIRSOI','ETP_AUTADM','SEJHC_SSR','SEJHC_MCO','SEJHP_MCO','SEJ_HTP_TOT','VEN_HDJ_TOT','VEN_HDN_TOT','SEAN_HEMO_CENTRE','SEAN_CHIMIO','SEAN_RADIO']]
Data = Data.merge(FINESS, on="FI", how="left")

In [26]:
Data.describe()

,ETPSAL_TOT,EFFLIB_TOT,ETP_INFSANSSPE,ETP_INFAVECSPE,ETP_AID,ETP_DIR,ETP_DIRSOI,ETP_AUTADM,SEJHC_SSR,SEJHC_MCO,SEJHP_MCO,SEJ_HTP_TOT,VEN_HDJ_TOT,VEN_HDN_TOT,SEAN_HEMO_CENTRE,SEAN_CHIMIO,SEAN_RADIO
count,3489.000000,1473.000000,3639.00000,1204.000000,3167.000000,2789.000000,1151.000000,3549.000000,1802.000000,1636.00000,1636.000000,512.000000,529.000000,210.000000,337.000000,728.000000,204.000000
mean,26.105374,28.909029,79.71737,25.843164,73.327335,2.790470,0.918566,37.527954,474.011654,6219.24022,4988.977995,1027.726562,7061.068053,399.300000,11950.632047,4425.013736,20058.475490
std,70.215511,46.663616,167.04529,48.049243,141.277774,3.788046,0.655406,80.022563,379.674641,9561.88067,6781.532895,1060.630557,6594.686080,1276.662635,7197.093938,5731.908423,13783.578855
min,0.000000,0.000000,0.01000,0.000000,0.050000,0.010000,0.000000,0.010000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.330000,3.000000,8.80000,1.927500,11.740000,1.000000,0.500000,3.300000,220.000000,321.00000,0.000000,395.750000,2251.000000,0.000000,7497.000000,450.500000,10787.250000
50%,3.890000,7.000000,20.00000,7.595000,26.500000,1.750000,1.000000,9.150000,377.000000,2183.00000,2400.000000,724.000000,5167.000000,0.000000,10988.000000,2281.000000,19352.500000
75%,10.980000,35.000000,59.53500,27.162500,65.925000,3.460000,1.000000,29.960000,633.750000,8175.25000,7426.000000,1320.750000,10084.000000,156.500000,15249.000000,6169.500000,28604.000000
max,949.030000,321.000000,1912.95000,542.870000,1863.290000,61.580000,6.000000,868.120000,2755.000000,75761.00000,54968.000000,11582.000000,41548.000000,12320.000000,47586.000000,37982.000000,61278.000000

In [27]:
Urg2022 = pd.read_csv("SAE/2022/URGENCES2_2022r.csv", sep=";", encoding="latin-1")
Urg2022 = Urg2022[['FI','PASSU']]
Data = Data.merge(Urg2022, on="FI", how="left")

In [28]:
USLD2022 = pd.read_csv("SAE/2022/USLD_2022r.csv", sep=";", encoding="latin-1")
USLD2022 = USLD2022[['FI','ENT']]
Data = Data.merge(USLD2022, on="FI", how="left")

In [29]:
SYGEN2022

,FI,FI_EJ,AN,LIT_MED,LIT_CHI,LIT_OBS,LIT_MCO,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,...,ACT_SCAN,NB_IRM,ACT_IRM,NB_CAM,ACT_CAM,NB_TOMO,ACT_TOMO,SAL_INTERV,POST_REVEIL,BOR
0,010000024,010780054,2022,270.0,68.0,47.0,385.0,14972.0,7260.0,3474.0,...,1.0,3.0,0.0,NaN,NaN,NaN,NaN,13.0,19.0,SYGEN
1,010000032,010780062,2022,66.0,17.0,8.0,91.0,4020.0,970.0,501.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,SYGEN
2,010000065,010780096,2022,59.0,NaN,NaN,59.0,1669.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3,010000081,010780112,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
4,010000099,010780120,2022,10.0,NaN,NaN,10.0,170.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3983,980500763,970407250,2022,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3984,980500920,970407250,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3985,980501159,970407250,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3986,980501258,970407250,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3987,980502298,980502280,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN

Total médecins (libéraux et saliariés confondus) :

In [30]:
Data['MED'] = Data['ETPSAL_TOT'] + Data['EFFLIB_TOT']

Total infirmiers (spécialisés et non-spécialisés) :

In [31]:
Data['IDE'] = Data['ETP_INFSANSSPE'] + Data['ETP_INFAVECSPE']

Total personnel administratif :

In [32]:
Data['ADMIN'] = Data['ETP_DIR'] + Data['ETP_DIRSOI'] + Data['ETP_AUTADM']

Total séjours MCO (hospitalisation partielle et complète confondu) :

In [33]:
Data['MCO'] = Data['SEJHC_MCO'] + Data['SEJHP_MCO']

Total séjours en psychiatrie (hospitalisations complètes, venues de jour et venues de nuit) :

In [34]:
Data['PSY'] = Data['SEJ_HTP_TOT'] + Data['VEN_HDJ_TOT'] + Data['VEN_HDN_TOT']

In [35]:
Data["SEANCES"] = Data['SEAN_HEMO_CENTRE'] + Data['SEAN_CHIMIO'] + Data['SEAN_RADIO']

Passage des variables d'intérêt en log (convention log(0) = 0) :

In [36]:
Data["lURG"] = np.where(Data["PASSU"] > 0, np.log(Data["PASSU"]), 0)
Data["lMCO"] = np.where(Data["MCO"] > 0, np.log(Data["MCO"]), 0)
Data["lPSY"] = np.where(Data["PSY"] > 0, np.log(Data["PSY"]), 0)
Data["lSSR"] = np.where(Data["SEJHC_SSR"] > 0, np.log(Data["SEJHC_SSR"]), 0)
Data["lSEANCES"] = np.where(Data["SEANCES"] > 0, np.log(Data["SEANCES"]), 0)
Data['lUSLD'] = np.where(Data['ENT'] > 0, np.log(Data['ENT']), 0)

Data["lMED"] = np.where(Data["MED"] > 0, np.log(Data["MED"]), 0)
Data["lIDE"] = np.where(Data["IDE"] > 0, np.log(Data["IDE"]), 0)
Data["lAID"] = np.where(Data["ETP_AID"] > 0, np.log(Data["ETP_AID"]), 0)
Data["lADMIN"] = np.where(Data["ADMIN"] > 0, np.log(Data["ADMIN"]), 0)

c:\Users\Alexandre\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\Alexandre\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\Alexandre\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\Alexandre\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\Alexandre\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

On construit deux variables de contrôle : Statut_PNL (resp. Statut_PL) vaut 1 si l'établissement est privé non lucratif (resp. privé lucratif)

In [37]:
dummies = pd.get_dummies(Data["Statut"], prefix="Statut")

Data["Statut_PNL"] = dummies["Statut_Privé non lucratif"]
Data["Statut_PL"]  = dummies["Statut_Privé lucratif"]

Data["Statut_PNL"] = Data["Statut_PNL"].astype(int)
Data["Statut_PL"]  = Data["Statut_PL"].astype(int)

Catégorisation des variables :

In [39]:
outputs = ["lURG", "lMCO", "lSSR", "lPSY","lSEANCES", "lUSLD"]
controls = ["Statut_PNL", "Statut_PL"]
inputs = ["lMED", "lIDE", "lAID", "lADMIN"]

Estimation des coefficients :

In [40]:
results = {}
dict = {}

for var in outputs:
    Data[f"{var}_PNL"] = Data[var] * Data["Statut_PNL"]
    Data[f"{var}_PL"]  = Data[var] * Data["Statut_PL"]


for inp in inputs:
    X = Data[outputs + controls + [f"{v}_PNL" for v in outputs] + [f"{v}_PL" for v in outputs]]
    X = sm.add_constant(X)
    y = Data[inp]
    
    model = sm.OLS(y, X).fit(cov_type="HC1")  # erreurs robustes
    results[inp] = model
    
    print("\n" + "="*60)
    print(f"Demande conditionnelle pour : {inp}")
    print(model.summary())
    
    print(inp)
    for c in controls:
        coef = model.params[c]
        pct = (np.exp(coef) - 1) * 100
        print(f"{c} → différence d'utilisation : {pct:.2f}%")
        dict[(inp,c)] = pct

============================================================
Demande conditionnelle pour : lMED
                            OLS Regression Results
==============================================================================
Dep. Variable:                   lMED   R-squared:                       0.472
Model:                            OLS   Adj. R-squared:                  0.470
Method:                 Least Squares   F-statistic:                     7671.
Date:                Wed, 04 Feb 2026   Prob (F-statistic):               0.00
Time:                        14:21:11   Log-Likelihood:                -6610.5
No. Observations:                4058   AIC:                         1.326e+04
Df Residuals:                    4037   BIC:                         1.340e+04
Df Model:                          20
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0793      0.059      1.347      0.178      -0.036       0.195
lURG             0.0695      0.014      5.043      0.000       0.042       0.097
lMCO             0.0911      0.013      7.200      0.000       0.066       0.116
lSSR             0.0141      0.014      1.005      0.315      -0.013       0.042
lPSY             0.0276      0.017      1.586      0.113      -0.006       0.062
lSEANCES         0.0167      0.035      0.471      0.637      -0.053       0.086
lUSLD           -0.0188      0.023     -0.823      0.411      -0.064       0.026
Statut_PNL       0.0866      0.065      1.333      0.183      -0.041       0.214
Statut_PL        0.6381      0.077      8.335      0.000       0.488       0.788
lURG_PNL         0.0488      0.045      1.085      0.278      -0.039       0.137
lMCO_PNL         0.0792      0.025      3.167      0.002       0.030       0.128
lSSR_PNL        -0.0231      0.017     -1.388      0.165      -0.056       0.010
lPSY_PNL         0.0533      0.043      1.238      0.216      -0.031       0.138
lSEANCES_PNL     0.3724      0.043      8.737      0.000       0.289       0.456
lUSLD_PNL       -0.0774      0.050     -1.551      0.121      -0.175       0.020
lURG_PL         -0.0051      0.017     -0.295      0.768      -0.039       0.029
lMCO_PL          0.2264      0.015     14.818      0.000       0.196       0.256
lSSR_PL         -0.0251      0.018     -1.428      0.153      -0.060       0.009
lPSY_PL          0.1012      0.026      3.945      0.000       0.051       0.152
lSEANCES_PL      0.0458      0.047      0.966      0.334      -0.047       0.139
lUSLD_PL         0.0308      0.080      0.386      0.700      -0.126       0.188
==============================================================================
Omnibus:                      609.740   Durbin-Watson:                   1.726
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1261.741
Skew:                           0.905   Prob(JB):                    1.04e-274
Kurtosis:                       5.047   Cond. No.                         48.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
lMED
Statut_PNL → différence d'utilisation : 9.05%
Statut_PL → différence d'utilisation : 89.30%

============================================================
Demande conditionnelle pour : lIDE
                            OLS Regression Results
==============================================================================
Dep. Variable:                   lIDE   R-squared:                       0.703
Model:                            OLS   Adj. R-squared:                  0.702
Method:                 Least Squares   F-statistic:                     7905.
Date:                Wed, 04 Feb 2026   Prob (F-statistic):               0.00
Time:                        14:21:11   Log-Likelihood:                -6752.9
No. Observations:                4058   AIC:                         1.355e+04
Df Residuals:                    4037   BIC:                         1.368e+04
Df Model:                          20
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.4580      0.076      6.018      0.000       0.309       0.607
lURG             0.2518      0.017     14.789      0.000       0.218       0.285
lMCO             0.2352      0.019     12.446      0.000       0.198       0.272
lSSR            -0.0801      0.014     -5.856      0.000      -0.107      -0.053
lPSY             0.2757      0.022     12.656      0.000       0.233       0.318
lSEANCES         0.1187      0.014      8.598      0.000       0.092       0.146
lUSLD           -0.0541      0.024     -2.267      0.023      -0.101      -0.007
Statut_PNL      -0.1789      0.083     -2.150      0.032      -0.342      -0.016
Statut_PL       -0.3878      0.083     -4.685      0.000      -0.550      -0.226
lURG_PNL        -0.0147      0.028     -0.522      0.602      -0.070       0.041
lMCO_PNL         0.0388      0.029      1.329      0.184      -0.018       0.096
lSSR_PNL         0.0489      0.018      2.687      0.007       0.013       0.085
lPSY_PNL        -0.2328      0.053     -4.354      0.000      -0.338      -0.128
lSEANCES_PNL     0.2042      0.028      7.319      0.000       0.150       0.259
lUSLD_PNL       -0.2088      0.058     -3.616      0.000      -0.322      -0.096
lURG_PL         -0.1435      0.024     -6.084      0.000      -0.190      -0.097
lMCO_PL          0.0887      0.022      4.092      0.000       0.046       0.131
lSSR_PL          0.0717      0.017      4.249      0.000       0.039       0.105
lPSY_PL         -0.2770      0.026    -10.606      0.000      -0.328      -0.226
lSEANCES_PL      0.0064      0.044      0.144      0.885      -0.081       0.093
lUSLD_PL        -0.0903      0.074     -1.224      0.221      -0.235       0.054
==============================================================================
Omnibus:                      530.492   Durbin-Watson:                   1.858
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2753.188
Skew:                           0.517   Prob(JB):                         0.00
Kurtosis:                       6.901   Cond. No.                         48.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
lIDE
Statut_PNL → différence d'utilisation : -16.38%
Statut_PL → différence d'utilisation : -32.14%

============================================================
Demande conditionnelle pour : lAID
                            OLS Regression Results
==============================================================================
Dep. Variable:                   lAID   R-squared:                       0.678
Model:                            OLS   Adj. R-squared:                  0.677
Method:                 Least Squares   F-statistic:                     1316.
Date:                Wed, 04 Feb 2026   Prob (F-statistic):               0.00
Time:                        14:21:11   Log-Likelihood:                -6063.3
No. Observations:                4058   AIC:                         1.217e+04
Df Residuals:                    4037   BIC:                         1.230e+04
Df Model:                          20
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            1.8511      0.069     26.760      0.000       1.716       1.987
lURG             0.0990      0.009     10.504      0.000       0.081       0.118
lMCO             0.1804      0.012     15.371      0.000       0.157       0.203
lSSR             0.0966      0.010      9.473      0.000       0.077       0.117
lPSY             0.1394      0.012     11.829      0.000       0.116       0.162
lSEANCES         0.0955      0.010      9.350      0.000       0.075       0.116
lUSLD            0.2154      0.015     14.409      0.000       0.186       0.245
Statut_PNL      -1.2114      0.081    -14.976      0.000      -1.370      -1.053
Statut_PL       -0.8000      0.088     -9.130      0.000      -0.972      -0.628
lURG_PNL         0.0098      0.024      0.405      0.686      -0.037       0.057
lMCO_PNL         0.0570      0.019      2.999      0.003       0.020       0.094
lSSR_PNL         0.2161      0.015     14.560      0.000       0.187       0.245
lPSY_PNL         0.1013      0.048      2.111      0.035       0.007       0.195
lSEANCES_PNL     0.1192      0.019      6.219      0.000       0.082       0.157
lUSLD_PNL        0.0629      0.058      1.089      0.276      -0.050       0.176
lURG_PL          0.0111      0.013      0.872      0.383      -0.014       0.036
lMCO_PL          0.0024      0.014      0.171      0.864      -0.025       0.030
lSSR_PL          0.1332      0.014      9.338      0.000       0.105       0.161
lPSY_PL         -0.0027      0.022     -0.123      0.902      -0.046       0.041
lSEANCES_PL     -0.0355      0.071     -0.497      0.619      -0.175       0.104
lUSLD_PL         0.1932      0.058      3.352      0.001       0.080       0.306
==============================================================================
Omnibus:                       83.070   Durbin-Watson:                   1.731
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              177.588
Skew:                          -0.023   Prob(JB):                     2.74e-39
Kurtosis:                       4.024   Cond. No.                         48.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
lAID
Statut_PNL → différence d'utilisation : -70.22%
Statut_PL → différence d'utilisation : -55.07%

============================================================
Demande conditionnelle pour : lADMIN
                            OLS Regression Results
==============================================================================
Dep. Variable:                 lADMIN   R-squared:                       0.451
Model:                            OLS   Adj. R-squared:                  0.448
Method:                 Least Squares   F-statistic:                     5399.
Date:                Wed, 04 Feb 2026   Prob (F-statistic):               0.00
Time:                        14:21:11   Log-Likelihood:                -7105.0
No. Observations:                4058   AIC:                         1.425e+04
Df Residuals:                    4037   BIC:                         1.438e+04
Df Model:                          20
Covariance Type:                  HC1
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.2821      0.075      3.780      0.000       0.136       0.428
lURG             0.1709      0.016     10.449      0.000       0.139       0.203
lMCO             0.1417      0.016      9.055      0.000       0.111       0.172
lSSR            -0.0669      0.015     -4.406      0.000      -0.097      -0.037
lPSY             0.2000      0.023      8.878      0.000       0.156       0.244
lSEANCES         0.1613      0.029      5.563      0.000       0.104       0.218
lUSLD           -0.0340      0.027     -1.268      0.205      -0.087       0.019
Statut_PNL      -0.0981      0.081     -1.211      0.226      -0.257       0.061
Statut_PL       -0.1624      0.082     -1.983      0.047      -0.323      -0.002
lURG_PNL        -0.1393      0.047     -2.952      0.003      -0.232      -0.047
lMCO_PNL         0.0803      0.028      2.848      0.004       0.025       0.136
lSSR_PNL         0.1250      0.020      6.179      0.000       0.085       0.165
lPSY_PNL        -0.0536      0.056     -0.955      0.339      -0.164       0.056
lSEANCES_PNL     0.1574      0.039      4.061      0.000       0.081       0.233
lUSLD_PNL       -0.0627      0.068     -0.925      0.355      -0.196       0.070
lURG_PL         -0.0492      0.024     -2.027      0.043      -0.097      -0.002
lMCO_PL          0.0293      0.019      1.539      0.124      -0.008       0.067
lSSR_PL          0.0972      0.018      5.273      0.000       0.061       0.133
lPSY_PL         -0.1308      0.031     -4.195      0.000      -0.192      -0.070
lSEANCES_PL     -0.1531      0.132     -1.161      0.245      -0.411       0.105
lUSLD_PL        -0.0249      0.063     -0.392      0.695      -0.149       0.099
==============================================================================
Omnibus:                      124.370   Durbin-Watson:                   1.761
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              295.666
Skew:                           0.127   Prob(JB):                     6.27e-65
Kurtosis:                       4.298   Cond. No.                         48.0
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)
lADMIN
Statut_PNL → différence d'utilisation : -9.34%
Statut_PL → différence d'utilisation : -14.99%

In [41]:
dict

{('lMED', 'Statut_PNL'): 9.046198853971998,
 ('lMED', 'Statut_PL'): 89.29525575772175,
 ('lIDE', 'Statut_PNL'): -16.37781477256297,
 ('lIDE', 'Statut_PL'): -32.143027743163785,
 ('lAID', 'Statut_PNL'): -70.22286505476518,
 ('lAID', 'Statut_PL'): -55.06680636513841,
 ('lADMIN', 'Statut_PNL'): -9.342415109437475,
 ('lADMIN', 'Statut_PL'): -14.98923007659625}

| Facteur   |    PL     |   PNL    |
|:----------|------------:|-------------:|
| ADMIN    |      -14.99 |        -9.34 |
| AID      |      -55.07 |       -70.22  |
| IDE      |      -32.14 |       -16.37 |
| MED      |      89.29 |         9.04 |

tableau regroupant les différences d'emploi de differences d'emploi de personnel à niveau de production égal selon la nature de l'etablissement (privé non lucratif ou privé lucratif) d'après les coefficients estimés. D'après les chiffres obtenus, les établissements privés sont plus économes en personnel administratif, en infirmiers et aides soignantes mais emploient plus de médecins à niveau de production égal.