Mise en place et importation des data

In [20]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

data = pd.read_csv('SAE/2022/SYGEN_2022r.csv', encoding='latin1', sep=';')
data.head()

,FI,FI_EJ,AN,LIT_MED,LIT_CHI,LIT_OBS,LIT_MCO,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,...,ACT_SCAN,NB_IRM,ACT_IRM,NB_CAM,ACT_CAM,NB_TOMO,ACT_TOMO,SAL_INTERV,POST_REVEIL,BOR
0,010000024,010780054,2022,270.0,68.0,47.0,385.0,14972.0,7260.0,3474.0,...,1.0,3.0,0.0,NaN,NaN,NaN,NaN,13.0,19.0,SYGEN
1,010000032,010780062,2022,66.0,17.0,8.0,91.0,4020.0,970.0,501.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,SYGEN
2,010000065,010780096,2022,59.0,NaN,NaN,59.0,1669.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
3,010000081,010780112,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN
4,010000099,010780120,2022,10.0,NaN,NaN,10.0,170.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN

On s'intéresse maintenant aux MCO et aux ETP correspondants

In [21]:
séjours = data[['FI','SEJHC_MCO','SEJHP_MCO']]
variables = data[['FI','ETPSAL_SPEMED', 'ETPSAL_SPECHI', 'ETP_INFAVECSPE', 'ETP_INFSANSSPE', 'ETP_AID', 'ETP_ASH']]
séjours.head()

          FI  SEJHC_MCO  SEJHP_MCO
0  010000024    25706.0      845.0
1  010000032     5491.0     1703.0
2  010000065     1669.0        0.0
3  010000081        NaN        NaN
4  010000099      170.0        0.0

In [22]:
variables.head()

,FI,ETPSAL_SPEMED,ETPSAL_SPECHI,ETP_INFAVECSPE,ETP_INFSANSSPE,ETP_AID,ETP_ASH
0,010000024,115.07,27.59,84.64,406.03,340.65,98.60
1,010000032,20.80,7.87,6.86,87.64,76.74,41.90
2,010000065,14.51,NaN,NaN,59.91,88.58,7.42
3,010000081,1.76,NaN,NaN,7.43,16.66,22.75
4,010000099,2.20,NaN,NaN,7.80,14.48,6.21

Première estimation

In [32]:
Y = séjours['SEJHC_MCO']
X = variables[['ETPSAL_SPEMED', 'ETPSAL_SPECHI', 'ETP_INFAVECSPE', 'ETP_INFSANSSPE', 'ETP_AID', 'ETP_ASH']]

In [33]:
# Remplace tous les NaN par 0 dans X pour le moment. 
X = X.fillna(0)

In [34]:
X = sm.add_constant(X)

model = sm.OLS(Y, X)
results_robust = model.fit(cov_type='HC1')

print(results_robust.summary())

ValueError: r_matrix performs f_test for using dimensions that are asymptotically non-normal