In [13]:
import pandas as pd
import numpy as np
from data import Urg2022_pub, UrgP2022, Urg2022_priv_luc, Urg2022_priv_non_luc

,BOR,AN,FI,RS,FI_EJ,URG,HMED,HIDE,SAO,ACC,...,dtEXT18,dtHOSP,LIT_UHCD,JLI_UHCD,SEJ_UHCD,SEJ0_UHCD,JOU_UHCD,STAP,RMM,Statut
0,URGENCES2,2022,010000024,CH DE FLEYRIAT,010780054,GEN,930.0,733.0,1.0,IAO,...,2.0,NaN,10.0,3650.0,2906.0,336.0,2927.0,1.0,1.0,Public
1,URGENCES2,2022,010000032,CH BUGEY SUD,010780062,GEN,168.0,168.0,0.0,NaN,...,14.0,NaN,4.0,1460.0,802.0,536.0,267.0,0.0,1.0,Public
2,URGENCES2,2022,010005239,CH DU HAUT BUGEY - GEOVREISSET,010008407,GEN,420.0,504.0,1.0,IAOMAO,...,46.0,NaN,5.0,NaN,1270.0,318.0,1094.0,1.0,0.0,Public
5,URGENCES2,2022,020000162,CH SAINT-QUENTIN,020000063,GEN,692.0,1008.0,1.0,IAO,...,1.0,NaN,10.0,3650.0,5887.0,1992.0,4813.0,1.0,0.0,Public
6,URGENCES2,2022,020000162,CH SAINT-QUENTIN,020000063,PED,168.0,420.0,0.0,NaN,...,NaN,2735.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,Public
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688,URGENCES2,2022,970400057,CHU SITE SUD (SAINT PIERRE),970408589,PED,216.0,35.0,1.0,IAO,...,NaN,4234.0,4.0,1460.0,1543.0,485.0,1147.0,NaN,NaN,Public
689,URGENCES2,2022,970400065,CH OUEST REUNION,970421038,GEN,450.0,903.0,1.0,IAOMAO,...,NaN,NaN,14.0,5110.0,6115.0,1024.0,5916.0,1.0,1.0,Public
690,URGENCES2,2022,970400065,CH OUEST REUNION,970421038,PED,54.0,336.0,NaN,IAO,...,NaN,3899.0,4.0,1460.0,2978.0,1789.0,1203.0,NaN,NaN,Public
691,URGENCES2,2022,970400073,GHER (SAINT-BENOIT),970403606,GEN,168.0,33.0,1.0,IAO,...,NaN,NaN,8.0,2920.0,3220.0,714.0,2728.0,0.0,1.0,Public
692,URGENCES2,2022,980500011,CHM,980500003,GEN,927.0,1382.0,1.0,IAO,...,0.0,NaN,18.0,6570.0,5713.0,870.0,9105.0,1.0,NaN,Public

In [ ]:
###---Productivité des médecins---

#Nombre de passages aux urgences par médecin en 2022 selon le secteur 

#Extraction du nombre d'ETP de médecins
Medecins2022 = UrgP2022[UrgP2022["PERSO"].isin(["M1000","M2000","M3020"])]
Medecins2022["ETPSAL"].fillna(0)
Medecins2022["EFFLIB"].fillna(0)
ETP_Medecins2022 = Medecins2022.groupby("FI",as_index=False)[["ETPSAL","EFFLIB"]].sum()
ETP_Medecins2022["tot"] = ETP_Medecins2022["EFFLIB"] + ETP_Medecins2022["ETPSAL"]
ETP_Medecins2022.describe()

           FI  ETPSAL  EFFLIB    tot
0   020000162    1.00     0.0   1.00
1   060000510    1.00     0.0   1.00
2   060000544    0.60     0.0   0.60
3   060780947    0.10     0.0   0.10
4   060785003    4.20     0.0   4.20
5   140000209    1.00     0.0   1.00
6   170000087    3.00     0.0   3.00
7   210987558    1.00     0.0   1.00
8   240000489    1.00     0.0   1.00
9   250006954    2.27     0.0   2.27
10  260000138    0.03     0.0   0.03
11  290000256    5.79     0.0   5.79
12  310783048    2.10     0.0   2.10
13  340000033    0.60     0.0   0.60
14  340024314    0.00     2.0   2.00
15  340785161    2.00     0.0   2.00
16  370004467    1.23     0.0   1.23
17  380000067    0.16     0.0   0.16
18  400000105    3.52     0.0   3.52
19  400000139    5.00     0.0   5.00
20  410000020    0.02     0.0   0.02
21  420000010    0.73     0.0   0.73
22  440000271    3.80     0.0   3.80
23  490000049    1.00     0.0   1.00
24  530000173    0.22     0.0   0.22
25  580972693    0.50     0.0   0.50
26  590000535    0.70     0.0   0.70
27  590796975    1.50     0.0   1.50
28  630000404    0.50     0.0   0.50
29  670000025    2.50     0.0   2.50
30  680000684    1.00     0.0   1.00
31  740000302    0.16     0.0   0.16
32  750000549    0.30     0.0   0.30
33  750100166    1.00     0.0   1.00
34  750803447    1.00     0.0   1.00
35  770000156    1.80     0.0   1.80
36  770000446    0.70     0.0   0.70
37  770019032    1.30     0.0   1.30
38  820000032    1.06     0.0   1.06
39  830000311    0.85     0.0   0.85
40  830000345    1.70     0.0   1.70
41  830100608    1.07     0.0   1.07
42  890975527    0.11     0.0   0.11
43  910020254    4.28     0.0   4.28
44  920000577    3.47     0.0   3.47
45  930000336    0.50     0.0   0.50
46  940000573   16.60     0.0  16.60
47  950000307    0.40     0.0   0.40
48  950000323    2.84     0.0   2.84
49  950000364    2.40     0.0   2.40
50  970300083    1.00     0.0   1.00

In [21]:

#Rassemble les médecins ETP avec le nombre de passages aux urgences selon le type d'établissement
#et calcule le ratio passages aux urgences/ETP médecins
Passages_pub = Urg2022_pub[["FI","PASSU"]]
Passages_pub = Passages_pub.merge(ETP_Medecins2022, left_on="FI", right_on="FI", how="left")
Passages_pub.dropna(inplace = True)
Passages_pub["ratio"] = Passages_pub["PASSU"]/Passages_pub["tot"]
Passages_pub["ratio"].describe()

In [ ]:
#privé lucratif
Passages_priv_luc = Urg2022_priv_luc[["FI","PASSU"]]
Passages_priv_luc = Passages_priv_luc.merge(ETP_Medecins2022, left_on="FI", right_on="FI", how="left")
Passages_priv_luc.dropna(inplace=TRUE)
Passages_priv_luc["ratio"] = Passages_priv_luc["PASSU"]/Passages_priv_luc["tot"]
Passages_priv_luc["ratio"].describe()

In [ ]:
#privé non lucratif
Passages_priv_nonluc = Urg2022_priv_non_luc[["FI","PASSU"]]
Passages_priv_nonluc = Passages_priv_nonluc.merge(ETP_Medecins2022, left_on="FI", right_on="FI", how="left")
Passages_priv_nonluc.dropna(inplace=True)
Passages_priv_nonluc["ratio"] = Passages_priv_nonluc["PASSU"]/Passages_priv_nonluc["tot"]
Passages_priv_nonluc["ratio"].describe()

In [ ]:
###--- Productivité des IDE ---

#Secteur public
Passages_pub = Urg2022_pub[["FI","PASSU","HIDE"]]
Passages_pub.groupby("FI",as_index=False)[["PASSU","HIDE"]].sum()
Passages_pub = Passages_pub.replace(0, np.nan).dropna()
Passages_pub["ratio"] = Passages_pub["PASSU"]/Passages_pub["HIDE"]
Passages_pub["ratio"].describe()

count     523.000000
mean       60.382621
std       102.119381
min         3.671102
25%        36.703995
50%        45.609489
75%        59.981821
max      1696.361111
Name: ratio, dtype: float64

In [16]:

#Secteur privé lucratif
Passages_priv_luc = Urg2022_priv_luc[["FI","PASSU","HIDE"]]
Passages_priv_luc.groupby("FI",as_index=False)[["PASSU","HIDE"]].sum()
Passages_priv_luc = Passages_priv_luc.replace(0, np.nan).dropna()
Passages_priv_luc["ratio"] = Passages_priv_luc["PASSU"]/Passages_priv_luc["HIDE"]
Passages_priv_luc["ratio"].describe()

count     121.000000
mean       71.466510
std       138.748197
min         6.250000
25%        43.501656
50%        53.571429
75%        68.755952
max      1503.411765
Name: ratio, dtype: float64

In [17]:

#Secteur privé non lucratif
Passages_priv_non_luc = Urg2022_priv_non_luc[["FI","PASSU","HIDE"]]
Passages_priv_non_luc.groupby("FI",as_index=False)[["PASSU","HIDE"]].sum()
Passages_priv_luc = Passages_priv_non_luc.replace(0, np.nan).dropna()
Passages_priv_non_luc["ratio"] = Passages_priv_non_luc["PASSU"]/Passages_priv_non_luc["HIDE"]
Passages_priv_non_luc["ratio"].describe()

C:\Users\roman\AppData\Local\Temp\ipykernel_6004\2980174334.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Passages_priv_non_luc["ratio"] = Passages_priv_non_luc["PASSU"]/Passages_priv_non_luc["HIDE"]

count     36.000000
mean      68.478455
std       86.184945
min        1.695901
25%       36.107463
50%       47.818013
75%       69.577142
max      522.714286
Name: ratio, dtype: float64

In [12]:
Urg2022_pub2 = Urg2022_pub[["PASSU","HMED","HIDE"]]
Urg2022_pub2 = Urg2022_pub2.dropna()
Urg2022_pub2 = Urg2022_pub2[(Urg2022_pub2 != 0).all(axis=1)]
Urg2022_pub2["ratiomed"] = Urg2022_pub2["PASSU"]/Urg2022_pub2["HMED"]
Urg2022_pub2["ratioinf"] = Urg2022_pub2["PASSU"]/Urg2022_pub2["HIDE"]
Urg2022_pub2["ratiomed"].describe()

count     520.000000
mean       96.341215
std        83.459165
min         1.502392
25%        65.788781
50%        83.587976
75%       104.572261
max      1387.931818
Name: ratiomed, dtype: float64

In [13]:
Urg2022_pub2["ratioinf"].describe()

count     520.000000
mean       60.246194
std       102.322477
min         3.671102
25%        36.713526
50%        45.580042
75%        59.431412
max      1696.361111
Name: ratioinf, dtype: float64

In [ ]:
Urg2022_luc2 = Urg2022_priv_luc[["PASSU","HMED","HIDE"]]
Urg2022_luc2 = Urg2022_luc2.dropna()
Urg2022_luc2 = Urg2022_luc2[(Urg2022_luc2 != 0).all(axis=1)]
Urg2022_luc2["ratiomed"] = Urg2022_luc2["PASSU"]/Urg2022_luc2["HMED"]
Urg2022_luc2["ratioinf"] = Urg2022_luc2["PASSU"]/Urg2022_luc2["HIDE"]
Urg2022_luc2["ratiomed"].describe()

count    121.000000
mean     105.417529
std       49.000575
min       14.285714
25%       82.574405
50%       99.496032
75%      117.717532
max      495.942857
Name: ratiomed, dtype: float64

In [16]:
Urg2022_luc2["ratioinf"].describe()

count     121.000000
mean       71.466510
std       138.748197
min         6.250000
25%        43.501656
50%        53.571429
75%        68.755952
max      1503.411765
Name: ratioinf, dtype: float64

In [23]:
Urg2022_nonluc2 = Urg2022_priv_non_luc[["PASSU","HMED","HIDE"]]
Urg2022_nonluc2 = Urg2022_nonluc2.dropna()
#Urg2022_nonluc2 = Urg2022_nonluc2[(Urg2022_nonluc2 != 0).all(axis=1)]
Urg2022_nonluc2["ratiomed"] = Urg2022_nonluc2["PASSU"]/Urg2022_nonluc2["HMED"]
Urg2022_nonluc2["ratioinf"] = Urg2022_nonluc2["PASSU"]/Urg2022_nonluc2["HIDE"]
Urg2022_nonluc2["ratiomed"].describe()

count     36.000000
mean      83.981134
std       33.015127
min        3.391801
25%       60.300935
50%       78.380407
75%      106.907738
max      174.420635
Name: ratiomed, dtype: float64